# Generated by Django 6.0.8 on 2026-09-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0008_dynamic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dynamic_type',
            field=models.CharField(
                choices=[
                    ('NONE', 'None'),
                    ('BMI', 'BMI'),
                    ('WHTR', 'Waist-to-height ratio'),
                    ('ONE_REP_MAX', '1RM'),
                    ('ONE_RM_TOTAL', '1RM total'),
                    ('SHOULDER_WAIST', 'Shoulder-to-waist ratio'),
                ],
                db_index=True,
                default='NONE',
                max_length=20,
            ),
        ),
    ]
