# Generated by Django 6.0.8 on 2026-09-27 12:42

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachGoal',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'weight_unit',
                    models.CharField(
                        choices=[('lb', 'lb'), ('kg', 'kg')], default='lb', max_length=2
                    ),
                ),
                ('start_date', models.DateField(default=datetime.date.today)),
                (
                    'start_weight',
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text='Leave empty to use your first weigh-in',
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(800),
                        ],
                    ),
                ),
                (
                    'target_weight',
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(800),
                        ],
                    ),
                ),
                ('target_date', models.DateField()),
                (
                    'rate_min_per_week',
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal('1.0'),
                        help_text='Weight lost (or gained) per week that still counts as on track',
                        max_digits=3,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='Slowest weekly change',
                    ),
                ),
                (
                    'rate_max_per_week',
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal('1.5'),
                        help_text='Faster than this and you risk losing muscle',
                        max_digits=3,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='Fastest weekly change',
                    ),
                ),
                (
                    'protein_target',
                    models.PositiveIntegerField(
                        default=165,
                        validators=[django.core.validators.MaxValueValidator(500)],
                        verbose_name='Daily protein (g)',
                    ),
                ),
                (
                    'step_target',
                    models.PositiveIntegerField(
                        default=10000,
                        validators=[django.core.validators.MaxValueValidator(100000)],
                        verbose_name='Daily steps',
                    ),
                ),
                (
                    'focus',
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Body parts to prioritise, see FocusArea',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='coach_goal',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
