# Generated by Django 6.0.8 on 2026-09-27 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coach', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('resolved', models.DateTimeField(blank=True, null=True)),
                ('rule', models.CharField(max_length=40)),
                ('key', models.CharField(max_length=120)),
                (
                    'severity',
                    models.CharField(
                        choices=[
                            ('good', 'On track'),
                            ('info', 'Note'),
                            ('adjust', 'Adjustment'),
                            ('warning', 'Warning'),
                        ],
                        max_length=10,
                    ),
                ),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('action', models.JSONField(blank=True, null=True)),
                ('action_label', models.CharField(blank=True, max_length=60)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('applied', 'Applied'),
                            ('dismissed', 'Dismissed'),
                        ],
                        default='pending',
                        max_length=10,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='coach_recommendations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [
                    models.Index(fields=['user', 'status'], name='coach_recom_user_id_d0bc7d_idx')
                ],
            },
        ),
    ]
