# Generated by Django 6.0.8 on 2026-09-27 13:01

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coach', '0002_recommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioSession',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateField(default=datetime.date.today)),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('incline_walk', 'Incline walk (treadmill)'),
                            ('outdoor_walk', 'Outdoor walk'),
                            ('run', 'Run'),
                            ('bike', 'Bike'),
                            ('stairs', 'Stair climber'),
                            ('other', 'Other'),
                        ],
                        default='incline_walk',
                        max_length=20,
                    ),
                ),
                (
                    'timing',
                    models.CharField(
                        choices=[
                            ('morning', 'Morning'),
                            ('post_workout', 'After lifting'),
                            ('other', 'Other time'),
                        ],
                        default='morning',
                        max_length=20,
                    ),
                ),
                (
                    'duration',
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(600),
                        ],
                        verbose_name='Duration (min)',
                    ),
                ),
                (
                    'incline',
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                        verbose_name='Incline (%)',
                    ),
                ),
                (
                    'speed',
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    'speed_unit',
                    models.CharField(
                        choices=[('mph', 'mph'), ('kmh', 'km/h')],
                        default='mph',
                        max_length=4,
                    ),
                ),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cardio_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-date', '-created'],
            },
        ),
    ]
